### ISSUE TITLE
Exception in handler: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

### ISSUE THREAD

**Issue by b12f** [openbikesensor/portal#301]
I'm still debugging this, but already creating an issue for SEO purposes.

```
portal_1    | Traceback (most recent call last):
portal_1    |   File "/usr/local/lib/python3.9/encodings/idna.py", line 165, in encode
portal_1    |     raise UnicodeError("label empty or too long")
portal_1    | UnicodeError: label empty or too long
portal_1    |
portal_1    | The above exception was the direct cause of the following exception:
portal_1    |
portal_1    | Traceback (most recent call last):
portal_1    |   File "handle_request", line 83, in handle_request
portal_1    |     from sanic.models.handler_types import ListenerType, MiddlewareType
portal_1    |   File "/opt/obs/api/obs/api/routes/tracks.py", line 76, in get_tracks
portal_1    |     return await _return_tracks(req, extend_query, limit, offset)
portal_1    |   File "/opt/obs/api/obs/api/routes/tracks.py", line 36, in _return_tracks
portal_1    |     track_count = await req.ctx.db.scalar(count_query)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 240, in scalar
portal_1    |     result = await self.execute(
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 214, in execute
portal_1    |     result = await greenlet_spawn(
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
portal_1    |     result = context.throw(*sys.exc_info())
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
portal_1    |     conn = self._connection_for_bind(bind)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
portal_1    |     return self._transaction._connection_for_bind(
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
portal_1    |     conn = bind.connect()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
portal_1    |     return super(Engine, self).connect()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
portal_1    |     return self._connection_cls(self, close_with_result=close_with_result)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
portal_1    |     else engine.raw_connection()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
portal_1    |     return self._wrap_pool_connect(self.pool.connect, _connection)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
portal_1    |     return fn()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 325, in connect
portal_1    |     return _ConnectionFairy._checkout(self)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 888, in _checkout
portal_1    |     fairy = _ConnectionRecord.checkout(pool)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 491, in checkout
portal_1    |     rec = pool._do_get()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
portal_1    |     self._dec_overflow()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
portal_1    |     compat.raise_(
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
portal_1    |     raise exception
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
portal_1    |     return self._create_connection()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 271, in _create_connection
portal_1    |     return _ConnectionRecord(self)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 386, in __init__
portal_1    |     self.__connect()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 685, in __connect
portal_1    |     pool.logger.debug("Error on connect(): %s", e)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
portal_1    |     compat.raise_(
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
portal_1    |     raise exception
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 680, in __connect
portal_1    |     self.dbapi_connection = connection = pool._invoke_creator(self)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
portal_1    |     return dialect.connect(*cargs, **cparams)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
portal_1    |     return self.dbapi.connect(*cargs, **cparams)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in connect
portal_1    |     await_only(self.asyncpg.connect(*arg, **kw)),
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
portal_1    |     return current.driver.switch(awaitable)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
portal_1    |     value = await result
portal_1    |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2045, in connect
portal_1    |     return await connect_utils._connect(
portal_1    |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 776, in _connect
portal_1    |     return await _connect_addr(
portal_1    |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 676, in _connect_addr
portal_1    |     return await __connect_addr(params, timeout, True, *args)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 720, in __connect_addr
portal_1    |     tr, pr = await compat.wait_for(connector, timeout=timeout)
portal_1    |   File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for
portal_1    |     return await asyncio.wait_for(fut, timeout)
portal_1    |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
portal_1    |     return fut.result()
portal_1    |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 586, in _create_ssl_connection
portal_1    |     tr, pr = await loop.create_connection(
portal_1    |   File "uvloop/loop.pyx", line 1941, in create_connection
portal_1    |   File "uvloop/loop.pyx", line 905, in uvloop.loop.Loop._getaddrinfo
portal_1    | UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

This only happens on calls that access the tracks database like `/api/stats`  or `/api/tracks`

**Comment by b12f** [comment]
python.org bug report: https://bugs.python.org/issue32958

**Comment by b12f** [comment]
Turns out to have been a misconfiguration. The `OBS_POSTGRES_URL` variable included a hostname with a zero-length part:

```
obs-portal-db.before..after.some.more.url.parts.com
```
